name: Ejecutar tracking semanal

on:
  schedule:
    - cron: "0 18 * * 1"   # Cada lunes a las 18:00 UTC (ajústalo a tu hora local)
  workflow_dispatch:        # Para ejecutarlo manualmente cuando quieras

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar script
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: python tracking.py
