name: Tracking MailAmericas

on:
  schedule:
    # Corre todos los lunes a las 13:00 UTC (09:00 Bolivia)
    - cron: "0 13 * * 1"
  workflow_dispatch: {} # Para correrlo manualmente

jobs:
  run-tracking:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Google Chrome (headless)
        id: chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tracking
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          RUN_HEADLESS: "true"
          CHROME_BINARY: ${{ steps.chrome.outputs.chrome-path }}
          TAB_TRACKING: "Tracking"   # cambia si tu pestaña tiene otro nombre
        run: python tracking.py
